apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-cfkw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-cfkw
    app.kubernetes.io/part-of: load-app-dbae2300-2eed-4032-aaaf-d6a79049e345
  name: devfile-sample-python-basic-cfkw
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-python-basic-cfkw
status:
  loadBalancer: {}
